### PR TITLE
Merge 178-components-base-mantine-remove-from-project into develop

### PR DESCRIPTION
**Pull request by kylescudder**
## What

Removed the mantine packages from the project.

## Why

We are now using shadcn-ui for our base components.

## How

Removed the package and made any necessary adjustments to resolve build errors.

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [x] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [x] All tests pass successfully
- [x] I have added/updated unit tests (if necessary)

## Additional Notes

The contents of the `AccountProfile.tsx1 have been commented out for now as this page is not currently in use and we be redone at some point anyway. It was just used for demo purposes for the different between shadcn-ui and Mantine components.

### CODE REVIEW

**Comment by f3rno64** [comment]
@kylescudder I don't have access to check why, but the deployment failed. Can you fix this?

**Comment by kylescudder** [comment]
> @kylescudder I don't have access to check why, but the deployment failed. Can you fix this?

@f3rno64 rebase and fix of a quick issue and build is working again now :)

**Review by f3rno64 — DISMISSED** [review]

**Comment by f3rno64** [comment]
@kylescudder can you rebase this?

**Review by f3rno64 — APPROVED** [review]

**Comment by f3rno64** [comment]
@kylescudder please review/approve this, as I rebased.

**Comment by kylescudder** [comment]
@f3rno64 I fixed a merge conflict, so this is back with you to approve 😂

**Review by f3rno64 — APPROVED** [review]

**Pull request merged**
