### PR TITLE
Secondary Navbar

### PR DESCRIPTION
**Pull request by Ve2s4**
## What

Implemented SecondaryNavbar.tsx component for individual group info pages.

## Why

Lets users to navigate between chats, material, qna and overview pages.

## How

Created a SecondaryNavbar.tsx component, modified the layout to share the common structure between chats, material, qna and overview.

## Related Issues

#510 

## Screenshots / GIFs (if applicable)

image

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [x] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [x] All tests pass successfully
- [x] I have added/updated unit tests (if necessary)

## Additional Notes

LFG!, lets merge this ASAP.

### CODE REVIEW

**Review by JacobHeldt — CHANGES_REQUESTED** [review]
Hey @Ve2s4! Thank you for working on this, the secondary navbar looks great! On my screen the navbar just is a bit narrow, with the text almost having no padding to the right. Can you please make sure that the spacing corresponds to our [Figma design](https://www.figma.com/design/fN8DRQmsIZ2zUQAfl559mL/Study-Groups-Secondary-Navbar?node-id=0-1&t=xqCU1qPB4NeyoVLM-1)? 
image
In addition, it would be great if the secondary navbar elements navigate to their corresponding sub-route in the group, as specified in the Figma file (like adding `/qna`) to the route when a user clicks the Q&A icon.

**Comment by Ve2s4** [comment]
Ahh shoot!, I forgot to change the fontsize and icon size based on the screen size, I got this.

**Comment by JacobHeldt** [comment]
No worries, thank you!

**Comment by Ve2s4** [comment]
image

**Review by JacobHeldt — APPROVED** [review]
Great, thank you @Ve2s4!

**Pull request merged**
