### PR TITLE
fix(root):  fix layout responsive

### PR DESCRIPTION
**Pull request by s3822042**
now the text will not cut off in middle screen

## What

The text in Mission section got cut off on middle screen

## Why

The text in Mission section will then display correctly in all resolution

## How

Change the tailwind responsive

## Related Issues

Issue #157 

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [x] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [x] All tests pass successfully
- [x] I have added/updated unit tests (if necessary)

### CODE REVIEW

**Review by JacobHeldt — CHANGES_REQUESTED** [review]
The text formatting looks good and the logo cloud is more responsive, thank you! There is still one issue on some smaller desktop resolutions, where the logo cloud gets cut off, as shown in the screenshot. 
Screenshot 2024-04-02 at 10 11 29 AM
Could you please fix this? Additionally, if the logo cloud size could be increased on very large resolutions, that would be great, since it appears small on monitors, as shown in this screenshot:
image

**Comment by s3822042** [comment]
> The text formatting looks good and the logo cloud is more responsive, thank you! There is still one issue on some smaller desktop resolutions, where the logo cloud gets cut off, as shown in the screenshot. Screenshot 2024-04-02 at 10 11 29 AM Could you please fix this? Additionally, if the logo cloud size could be increased on very large resolutions, that would be great, since it appears small on monitors, as shown in this screenshot: image

fixed it, please check again @JacobHeldt

**Review by JacobHeldt — CHANGES_REQUESTED** [review]
Thank you @s3822042! The logo cloud position now looks great on all screen resulotions larger than iPad. There are two issues that still have to be addressed:
- The shape of the mission section arrow does not correspond anymore to the desired design as defined in this [Figma file](https://www.figma.com/file/uchLohwINP93Y0TKtUQOSU/StudyCrew-Homepage?type=design&node-id=0%3A1&mode=design&t=tDvzL7g3ghL11t4T-1).
image
- Now, the logo cloud seems to be displayed on mobile devices as well, which does not correspond to the desired design as defined in the figma file.

**Comment by s3822042** [comment]
sorry for the oversight, it should be fixed now

**Review by JacobHeldt — APPROVED** [review]

**Pull request merged**
