### PR TITLE
Margins Fixed i122 i123 i124

### PR DESCRIPTION
**Pull request by zaibutcooler**
## What

I made changes in the margins for the issues #122, #123, #124

## Why

Looks bad on the mobile responsive view.

## How

First I added max-width for one of the issue,  second, I added padding-x . third one I adjust padding x and y. and adjust some styling to look good on mobile view as you mentioned.

## Related Issues

Nope, only one thing. Vanila CSS is hard to navigate and messy. Should probably avoid using it next time. 

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [ ] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [ ] All tests pass successfully
- [x] I have added/updated unit tests (if necessary)

## Additional Notes

Sorry for the misconnection. I didn't write descriptions cuz it's not a heavy task at all. Will try ot avoid it later on.

### CODE REVIEW

**Comment by kylescudder** [comment]
Hi @zaiYellYintAung thank you for contributing to our project! Could I please ask that you fill in the PR template, as I am not sure of a few things right now:

What is your PR doing?
Why is it being done?
How have you achieved it?
If it would be useful for the reviewer, could you please include screenshots? If a before and after image would make things clearer, please include that.

Can you please make sure that your changes conform with our linting standards? As you can see from the PR, you changes has changed a number of files with formatting changes (capitalisation, semicolons etc) which make it very difficult to see what are real changes, and what are just refactoring changes.

If you are unsure about anything I have asked, just let me know :)  

Thank you!

**Review by JacobHeldt — APPROVED** [review]

**Comment by kylescudder** [comment]
Hi @zaiYellYintAung thank you for adjusting your PR to include more information. Could you please also address the linting issues I have mentioned?

**Comment by kylescudder** [comment]
@zaibutcooler please rebase and run `pnpm format` & commit/push.

**Comment by kylescudder** [comment]
@zaibutcooler please resolve the merge conflicts after the rebase. The structure of the project is now quite different so these merge conflicts might be quite different.

**Pull request closed without merging**
