### PR TITLE
Fix: Set ESLint linebreak-style based on platform

### PR DESCRIPTION
**Pull request by f3rno64**
## What

As I develop on Linux (via WSL), ESLint complains about the line endings used.

## Why

We should support developers using either Windows or Linux environments.

## How

Makes the ESLint config a JS file and sets the `linebreak-style` property based on the platform.

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [x] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [x] All tests pass successfully
- [x] I have added/updated unit tests (if necessary)

### CODE REVIEW

**Comment by kylescudder** [comment]
Hi @f3rno64 thank you for submitting a PR to our project. 

Can you please make sure in the future that you submit an issue to the project, with details of the specific problem/new feature you are trying to address? 

Vague or non-descript issues make if difficult for reviewers to know exactly what issue they are trying to review. Can you please try and specific what exact issue you are experiencing and avoid generalities like "compiler doesn't like it" or "getting build errors.".

You also seem to have changed the eslint file from a JSON file to a JS file with no explanation as to why this has been done.

**Comment by f3rno64** [comment]
> Hi @f3rno64 thank you for submitting a PR to our project.
> 
> Can you please make sure in the future that you submit an issue to the project, with details of the specific problem/new feature you are trying to address?
> 
> Vague or non-descript issues make if difficult for reviewers to know exactly what issue they are trying to review. Can you please try and specific what exact issue you are experiencing and avoid generalities like "compiler doesn't like it" or "getting build errors.".
> 
> You also seem to have changed the eslint file from a JSON file to a JS file with no explanation as to why this has been done.

The change to a JS file was to access `process.platform`, to allow for a dynamic line-ending setting based on the platform.

In the future I'll open an issue, sure, sorry about that. This was my first contribution and I wasn't informed of the steps to take.

I see you've merged `develop` into this branch; in the future let's go with a rebase instead, it's much cleaner. My actual changes on this PR seem to be completely gone now. I'll go ahead and fix that.

**Comment by f3rno64** [comment]
@kylescudder This confused me for a bit, but it seems that since you've merged my other PR, this one also got merged in as I had branched off of it to work on the other one. Otherwise, locally, my editor was giving me tons of line-break errors.

In the future, I'll make it clear if a PR branches off of another one, as they need to be merged in order. Let's also avoid merging `develop` into PRs, and rebase instead.

**Comment by kylescudder** [comment]
> > Hi @f3rno64 thank you for submitting a PR to our project.
> > Can you please make sure in the future that you submit an issue to the project, with details of the specific problem/new feature you are trying to address?
> > Vague or non-descript issues make if difficult for reviewers to know exactly what issue they are trying to review. Can you please try and specific what exact issue you are experiencing and avoid generalities like "compiler doesn't like it" or "getting build errors.".
> > You also seem to have changed the eslint file from a JSON file to a JS file with no explanation as to why this has been done.
> 
> The change to a JS file was to access `process.platform`, to allow for a dynamic line-ending setting based on the platform.
> 
> In the future I'll open an issue, sure, sorry about that. This was my first contribution and I wasn't informed of the steps to take.
> 
> I see you've merged `develop` into this branch; in the future let's go with a rebase instead, it's much cleaner. My actual changes on this PR seem to be completely gone now. I'll go ahead and fix that.

I did not merge develop into your branch, this PR had merge conflicts in the `.eslintrc`, which I resolved.

Your changes were not in the resolved version of the file, as you added a new linting rule condition, which is not the kind of decision that we make without a discussion first.

**Comment by kylescudder** [comment]
> @kylescudder This confused me for a bit, but it seems that since you've merged my other PR, this one also got merged in as I had branched off of it to work on the other one. Otherwise, locally, my editor was giving me tons of line-break errors.
> 
> In the future, I'll make it clear if a PR branches off of another one, as they need to be merged in order. Let's also avoid merging `develop` into PRs, and rebase instead.

Please see my other comment for context.

**Comment by kylescudder** [comment]
@f3rno64 if you would like to add an issue and then create a PR to resolve that and submit it again, I would be more than happy to review it for you.

**Pull request closed without merging**
