### PR TITLE
Refactor/Fix: Features Component Mobile Layout

### PR DESCRIPTION
**Pull request by f3rno64**
## What

Target Issue: https://github.com/StudyCrew/StudyCrew/issues/125

Refactors the `Features` component; moves the feature data into a soon-to-be-project-wide `const.ts` file in the component directory, types it, and modifies the `Features` component to only ever render the active feature stage data.

Adjusts the `Features` component, adding a mobile layout where only a single card is shown, with controls to view the next/previous card.

## Why

The existing code was messy, and rendered all stages at once, hiding those that were inactive. It did not type the stage data (title, description, etc) and was modifying the class names in a manual way. Adding the `classnames` dep cleans this up nicely.

## How

TODO

## Checklist

- [x] I have tested these changes locally
- [x] I have ensured my code follows the project's coding style
- [x] I have updated the documentation accordingly
- [x] My changes do not introduce any new warnings or errors
- [x] All tests pass successfully
- [x] I have added/updated unit tests (if necessary)

### CODE REVIEW

**Review by kylescudder — APPROVED** [review]

**Comment by kylescudder** [comment]
@f3rno64 I know this is WIP but just as a heads up, the Vercel build failed with the following:

image

**Comment by f3rno64** [comment]
> @f3rno64 I know this is WIP but just as a heads up, the Vercel build failed with the following:
> 
> image

@kylescudder Just pushed 16c980c which should fix this.

**Comment by f3rno64** [comment]
@kylescudder @JacobHeldt this is ready for review. I will refactor the styles to remove unneeded CSS later, for now I just wanted to refactor the component and fix the actual issue with the mobile layout. Both are now done.

**Comment by kylescudder** [comment]
Reviewing now.

**Review by kylescudder — DISMISSED** [review]

**Comment by kylescudder** [comment]
@JacobHeldt please can you also review and approve these changes, then we can publish to production

**Review by JacobHeldt — APPROVED** [review]

**Review by kylescudder — APPROVED** [review]

**Pull request merged**
